import type { MotivationTab } from "./motivation";

type MotivationItem = { title: string; body: string };

export const english: Record<MotivationTab, MotivationItem[]> = {
  "Daily Quote": [
    { title: "Begin Again", body: "A difficult day is not a verdict. It is a page asking for a braver sentence." },
    { title: "Small Wins", body: "Change becomes real when one small promise is kept quietly, repeatedly, and with love." },
    { title: "Steady Heart", body: "You do not need a perfect mood to move forward. You only need the next honest step." },
    { title: "Embrace the Unknown", body: "Do not fear the path you cannot see. Your steps will create it as you walk." },
    { title: "The Power of Now", body: "The past is an illusion, the future is a guess. Right now is where all your power lies." },
    { title: "Gentle Progress", body: "Rivers do not rush, yet they carve through mountains over time. Be patient with your progress." },
    { title: "Inner Light", body: "Even the darkest room is conquered by a single candle. Let your inner light guide you." },
    { title: "Brave Choices", body: "Every morning brings a new choice. Choose courage over comfort today." },
    { title: "Silent Strength", body: "Sometimes the strongest thing you can do is just to keep breathing and keep walking." },
    { title: "Unseen Growth", body: "The roots grow deep before the tree reaches the sky. Do not rush your foundation." },
    { title: "Focus Within", body: "Look outward to dream, but look inward to awaken your true potential." },
    { title: "Grace in Failure", body: "Failure is not the opposite of success; it is a stepping stone on the path to mastery." },
    { title: "Quiet Resolve", body: "You don't need to shout your goals. Let your quiet resolve speak through your actions." },
    { title: "Infinite Potential", body: "You are the universe expressing itself as a human for a little while. Act accordingly." },
    { title: "Trust the Process", body: "Not every chapter makes sense until the book is finished. Keep writing your story." },
    { title: "Radical Acceptance", body: "Accept what is, let go of what was, and have faith in what will be." },
    { title: "Enduring Spirit", body: "Your spirit is forged in the fires of adversity. Do not curse the flame; embrace the forging." },
    { title: "Present Moment", body: "Life is happening right now, not in the memory of yesterday or the imagination of tomorrow." },
    { title: "Fierce Compassion", body: "Be gentle with your mistakes, but fierce in your determination to learn from them." },
    { title: "Unbreakable Will", body: "The human will can bend endlessly before it breaks. You are far stronger than you realize." },
    { title: "Daily Rebirth", body: "Each sunrise is a reset button for your soul. Press it with gratitude and intention." },
    { title: "The Art of Letting Go", body: "Sometimes the heaviest burden is simply the refusal to let go of what no longer serves you." },
    { title: "Purposeful Action", body: "Do not act just to be busy. Act with purpose, even if the action is simply resting." },
    { title: "Resilient Mind", body: "A resilient mind does not avoid the storm; it learns how to build a windmill from the gale." },
    { title: "Uncharted Waters", body: "You cannot discover new oceans unless you have the courage to lose sight of the shore." },
    { title: "Quiet Confidence", body: "True confidence whispers, it does not roar. Let your results be your loudest voice." },
    { title: "Endless Curiosity", body: "Stay curious. The moment you think you know everything is the moment you stop growing." },
    { title: "The Gift of Time", body: "Time is the only currency you can never earn back. Spend it on what truly matters." },
    { title: "Unwavering Faith", body: "Faith is taking the first step even when you don't see the whole staircase." },
    { title: "Boundless Love", body: "Start by loving yourself deeply, and watch how that love changes everything around you." },
    { title: "The Final Step", body: "The hardest step is always the last one before the summit. Push through the exhaustion." }
  ],
  "Success Story": [
    { title: "The Ten-Minute Builder", body: "A student who felt behind began with ten focused minutes every morning. Six months later, those minutes had become a skill, a portfolio, and proof that discipline can start gently." },
    { title: "The Quiet Reset", body: "A tired professional replaced late-night scrolling with one written reflection. The first week felt tiny. The second felt clearer. By the third, decisions stopped feeling foggy." },
    { title: "The Relentless Artist", body: "An artist threw away 100 bad sketches without despair, knowing the 101st would hold the magic. Perseverance is the true medium of art." },
    { title: "The Humble Leader", body: "A manager stepped down to listen to the lowest-paid worker. By changing the factory floor, he transformed the entire company's culture." },
    { title: "The Persistent Scholar", body: "Rejected 12 times, the author continued writing. The 13th publisher saw the genius. Patience outlasts rejection." },
    { title: "The Resilient Athlete", body: "After a devastating injury, the runner focused on strengthening her mind. She returned not just physically healed, but mentally invincible." },
    { title: "The Innovator's Pivot", body: "When their primary product failed, the team focused on a tiny side-feature. That feature became a billion-dollar platform." },
    { title: "The Silent Contributor", body: "She didn't speak loudly in meetings, but her meticulous code prevented a catastrophic failure. Quiet competence is a superpower." },
    { title: "The Late Bloomer", body: "He started learning piano at 60. By 70, he was performing locally. It is never too late to begin a new masterpiece." },
    { title: "The Patient Gardener", body: "A barren plot took five years of relentless tending before it yielded fruit. True growth requires unwavering patience." },
    { title: "The Fearless Speaker", body: "Terrified of crowds, he practiced speaking to empty chairs for months. When the audience finally arrived, he was ready." },
    { title: "The Focused Student", body: "She turned off her phone for two hours every day to study. Those uninterrupted hours became the foundation of her career." },
    { title: "The Generous Mentor", body: "By spending an hour a week helping a junior employee, he unknowingly trained the person who would one day save his company." },
    { title: "The Optimistic Traveler", body: "Lost in a foreign city without a map, she chose to see it as an adventure. She found a hidden cafe she never would have searched for." },
    { title: "The Steady Climber", body: "He didn't look at the peak, only at the next foothold. One day, he looked up and realized he was at the top." },
    { title: "The Adapting Business", body: "When the market shifted, they didn't complain. They retooled their machines in a weekend and survived the crisis." },
    { title: "The Forgiving Friend", body: "He chose to forgive a bitter argument. That grace saved a friendship that lasted for another forty years." },
    { title: "The Mindful Eater", body: "By chewing slowly and eating only until satisfied, she healed her relationship with food and found unexpected energy." },
    { title: "The Dedicated Writer", body: "He wrote 500 words a day, rain or shine. In a year, he had a novel. Small daily actions create massive results." },
    { title: "The Brave Entrepreneur", body: "She launched her product before it was 'perfect'. The feedback she received made the second version brilliant." },
    { title: "The Calm Negotiator", body: "By pausing for three seconds before every reply, he turned a hostile negotiation into a collaborative partnership." },
    { title: "The Minimalist's Joy", body: "He sold half his belongings. With less to manage, he finally found the time to pursue his true passion." },
    { title: "The Consistent Saver", body: "Saving just 5% of her income seemed useless at first. Compounding interest made it a fortune two decades later." },
    { title: "The Honest Apology", body: "A CEO publicly admitted a mistake instead of hiding it. The resulting trust from customers skyrocketed their brand loyalty." },
    { title: "The Creative Constraint", body: "Given only two colors to paint with, the artist discovered a totally new style that defined their entire career." },
    { title: "The Empathetic Listener", body: "She didn't offer solutions, she just listened. Her silence helped her friend find their own answer." },
    { title: "The Unlikely Alliance", body: "Two competitors decided to share research instead of fighting. Together, they cured a disease." },
    { title: "The Daily Walker", body: "A 20-minute walk every evening cleared his mind. Those walks birthed the ideas that changed his life." },
    { title: "The Joyful Volunteer", body: "He gave his weekends to the shelter. In giving his time, he found the purpose he had been searching for." },
    { title: "The Grateful Heart", body: "She started writing three things she was grateful for every night. Her perspective shifted, and so did her reality." },
    { title: "The Final Push", body: "Exhausted and ready to quit, he promised himself one more try. That final try was the breakthrough." }
  ],
  "Premanand Maharaj Thoughts": [
    { title: "Remember The Inner Seat", body: "Sit for a moment with devotion before reacting. A calm remembrance can turn anger into patience and confusion into surrender." },
    { title: "Clean Intention", body: "When the intention is pure, even a small action carries spiritual strength. Do the next duty with humility." },
    { title: "The Name is Enough", body: "In the darkest moments, simply chanting the holy name with love dissolves the deepest anxieties." },
    { title: "See God in All", body: "Treat every soul you meet as a temple. When you serve others with this vision, you are serving the Divine." },
    { title: "Surrender the Result", body: "Do your prescribed duty perfectly, but leave the outcome at the lotus feet of the Lord. Peace lives there." },
    { title: "The True Wealth", body: "Material wealth can be stolen or lost. The wealth of devotion to God is eternal and only grows when shared." },
    { title: "Control the Tongue", body: "What you eat and what you speak shape your spiritual reality. Keep both pure and dedicated to the Lord." },
    { title: "The Power of Satsang", body: "Good company elevates the soul. Seek out those who discuss divine pastimes, and avoid worldly gossip." },
    { title: "Acceptance is Peace", body: "Whatever happens is the will of the Beloved. Accept joy and sorrow equally as His Prasad (blessing)." },
    { title: "Tears of Love", body: "Tears shed in longing for the Divine wash away lifetimes of accumulated karma. Do not hide them." },
    { title: "The Ego's Trick", body: "The ego convinces you that you are the doer. Realize that you are merely an instrument in His divine hands." },
    { title: "Unbroken Remembrance", body: "Just as a river flows continuously to the ocean, let your mind flow continuously towards God, even while working." },
    { title: "The Highest Charity", body: "Feeding the hungry is great, but giving someone the name of God is the highest charity, for it feeds the soul eternally." },
    { title: "Forgive Instantly", body: "Holding a grudge blocks the flow of grace. Forgive instantly, knowing the Lord is orchestrating all events." },
    { title: "The Shelter of Saints", body: "The dust from the feet of a true saint is more purifying than a thousand holy rivers. Seek their blessings." },
    { title: "Simplicity of Heart", body: "God does not care for intellectual gymnastics. He is won over by the simple, innocent love of a pure heart." },
    { title: "The Illusion of Time", body: "Do not waste this precious human birth chasing temporary pleasures. Dedicate this time to realizing the Eternal." },
    { title: "Chant with Feeling", body: "A single name chanted with a crying heart is more powerful than millions chanted mechanically." },
    { title: "The Divine Mother", body: "Seek the shelter of Radha Rani. Her grace is the swift and certain path to the Supreme." },
    { title: "Patience in Sadhan", body: "Spiritual progress is not always visible. Keep practicing your sadhana (discipline) with unwavering patience." },
    { title: "The Disease of Comparison", body: "Do not compare your spiritual journey to others. God has a unique relationship with every single soul." },
    { title: "Humility is the Key", body: "As long as there is pride, God remains distant. Become smaller than a blade of grass to invite Him in." },
    { title: "The Value of Silence", body: "Speak only when necessary. In deep silence, the voice of the Divine can finally be heard." },
    { title: "Dependence on Him", body: "Stop relying on your own strength or intellect. Complete dependence on God is the highest freedom." },
    { title: "The Joy of Service", body: "Seva (selfless service) is not a chore; it is the privilege of participating in God's divine play." },
    { title: "Overcoming Fear", body: "Fear only exists when you forget that the Lord of the Universe is holding your hand. Remember Him and be fearless." },
    { title: "The Purity of Tears", body: "When the heart melts in divine love, the resulting tears purify the mind completely." },
    { title: "The True Guru", body: "A true Guru does not just teach; he awakens the dormant love for God within your heart." },
    { title: "The Nature of the World", body: "The world is a passing dream. Do not become deeply attached to its shadows; seek the eternal substance." },
    { title: "The Power of Faith", body: "Even a small fraction of genuine faith can move mountains of past karma. Trust His timing implicitly." },
    { title: "The Final Goal", body: "The ultimate goal is not liberation, but selfless, continuous, unmotivated love for the Supreme Lord." }
  ],
  "Bhagavad Gita Verse": [
    { title: "Karmanye Vadhikaraste (2.47)", body: "You have a right to your action, not to ownership of every result. Work sincerely and let attachment become lighter." },
    { title: "Balanced Mind (2.48)", body: "A steady mind meets success and difficulty without losing its center. Practice balance in the smallest moments." },
    { title: "The Eternal Soul (2.20)", body: "The soul is never born and never dies. Knowing this, face life's challenges with fearless determination." },
    { title: "Control the Mind (6.6)", body: "For him who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his very mind will be the greatest enemy." },
    { title: "Path of Devotion (9.26)", body: "If one offers Me with love and devotion a leaf, a flower, fruit or water, I will accept it. Purity of heart is what matters." },
    { title: "Overcoming Lust and Anger (3.37)", body: "It is lust only, Arjuna, which is born of contact with the material mode of passion and later transformed into wrath, and which is the all-devouring sinful enemy of this world." },
    { title: "The Value of Equanimity (2.14)", body: "O son of Kunti, the nonpermanent appearance of happiness and distress, and their disappearance in due course, are like the appearance and disappearance of winter and summer seasons." },
    { title: "Self-Realization (6.5)", body: "A man must elevate himself by his own mind, not degrade himself. The mind is the friend of the conditioned soul, and his enemy as well." },
    { title: "Action Without Attachment (3.19)", body: "Therefore, without being attached to the fruits of activities, one should act as a matter of duty, for by working without attachment one attains the Supreme." },
    { title: "The Supreme Abode (8.21)", body: "That which the Vedantists describe as unmanifest and infallible, that which is known as the supreme destination, that place from which, having attained it, one never returns—that is My supreme abode." },
    { title: "Faith and Knowledge (4.39)", body: "A faithful man who is dedicated to transcendental knowledge and who subdues his senses is eligible to achieve such knowledge, and having achieved it he quickly attains the supreme spiritual peace." },
    { title: "The Yoga of Meditation (6.19)", body: "As a lamp in a windless place does not waver, so the transcendentalist, whose mind is controlled, remains always steady in his meditation on the transcendent Self." },
    { title: "Divine Love (12.13-14)", body: "One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress... such a devotee of Mine is very dear to Me." },
    { title: "The Power of Time (11.32)", body: "Time I am, the great destroyer of the worlds, and I have come here to destroy all people. Do your duty without fear of the inevitable." },
    { title: "True Renunciation (18.2)", body: "The giving up of activities that are based on material desire is what great learned men call the renounced order of life. And giving up the results of all activities is what the wise call renunciation." },
    { title: "The Modes of Nature (14.5)", body: "Material nature consists of three modes—goodness, passion and ignorance. When the eternal living entity comes in contact with nature, he becomes conditioned by these modes." },
    { title: "Overcoming Maya (7.14)", body: "This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it." },
    { title: "The Sight of the Wise (5.18)", body: "The humble sages, by virtue of true knowledge, see with equal vision a learned and gentle brahmana, a cow, an elephant, a dog and a dog-eater." },
    { title: "The Inner Controller (18.61)", body: "The Supreme Lord is situated in everyone's heart, O Arjuna, and is directing the wanderings of all living entities, who are seated as on a machine, made of the material energy." },
    { title: "Surrender (18.66)", body: "Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear." },
    { title: "The Steady Intellect (2.56)", body: "One who is not disturbed in mind even amidst the threefold miseries or elated when there is happiness, and who is free from attachment, fear and anger, is called a sage of steady mind." },
    { title: "Work as Sacrifice (3.9)", body: "Work done as a sacrifice for Visnu has to be performed; otherwise work causes bondage in this material world. Therefore, perform your prescribed duties for His satisfaction." },
    { title: "The Demoniac and Divine (16.1-3)", body: "Fearlessness; purification of one's existence; cultivation of spiritual knowledge; charity; self-control; performance of sacrifice; study of the Vedas; austerity; simplicity; nonviolence; truthfulness... these are divine qualities." },
    { title: "The Root of Suffering (2.62-63)", body: "While contemplating the objects of the senses, a person develops attachment for them... from anger, complete delusion arises, and from delusion bewilderment of memory." },
    { title: "The Universal Form (11.12)", body: "If hundreds of thousands of suns were to rise at once into the sky, their radiance might resemble the effulgence of the Supreme Person in that universal form." },
    { title: "The Perfection of Yoga (6.47)", body: "And of all yogis, the one with great faith who always abides in Me, thinks of Me within himself and renders transcendental loving service to Me—he is the most intimately united with Me in yoga." },
    { title: "The Immortal Soul (2.23)", body: "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind." },
    { title: "The Highest Knowledge (9.2)", body: "This knowledge is the king of education, the most secret of all secrets. It is the purest knowledge, and because it gives direct perception of the self by realization, it is the perfection of religion." },
    { title: "The Mind's Restlessness (6.34)", body: "The mind is restless, turbulent, obstinate and very strong, O Krishna, and to subdue it, I think, is more difficult than controlling the wind." },
    { title: "The Assurance of Krishna (9.31)", body: "He quickly becomes righteous and attains lasting peace. O son of Kunti, declare it boldly that My devotee never perishes." },
    { title: "The Final Word (18.78)", body: "Wherever there is Krishna, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will also certainly be opulence, victory, extraordinary power, and morality." }
  ],
  "Today's Challenge": [
    { title: "One Honest Repair", body: "Fix one small thing you have been postponing: a message, a corner of your room, a task, or an apology." },
    { title: "No Complaint Hour", body: "Spend one hour without complaining. Replace each complaint with one useful action." },
    { title: "Digital Fast", body: "Spend the first hour of your day completely screen-free. Read, write, or simply sit." },
    { title: "Hydration Focus", body: "Drink one full glass of water immediately upon waking, and maintain hydration all day." },
    { title: "The 10-Minute Walk", body: "Take a 10-minute walk outside without headphones. Listen to the world." },
    { title: "Express Gratitude", body: "Send a message to someone explaining why you appreciate them. Do not expect a reply." },
    { title: "Clean Your Workspace", body: "Take 15 minutes to completely clear your physical workspace. A clear desk creates a clear mind." },
    { title: "The Silent Meal", body: "Eat one meal today in complete silence, focusing entirely on the taste and texture of the food." },
    { title: "Read 10 Pages", body: "Read 10 pages of a physical book that challenges your perspective or teaches you something new." },
    { title: "Postpone Judgment", body: "Catch yourself judging someone today, and actively replace that thought with curiosity." },
    { title: "The 5-Minute Meditate", body: "Sit in silence for exactly 5 minutes. Focus only on the sensation of your breath." },
    { title: "Unsubscribe", body: "Unsubscribe from 5 promotional emails or unfollow 5 social media accounts that drain your energy." },
    { title: "Write a Goal", body: "Write down your primary goal for this month on a piece of paper and tape it where you will see it daily." },
    { title: "Stretch", body: "Spend 5 minutes doing deep, slow stretching before going to bed tonight." },
    { title: "No Sugar Day", body: "Avoid all added sugars for the entire day. Notice how your energy levels stabilize." },
    { title: "Learn One Word", body: "Learn a new word in a language you don't speak, and use it in your mind throughout the day." },
    { title: "Compliment a Stranger", body: "Give a genuine compliment to someone you don't know well. Watch their face light up." },
    { title: "The Cold Shower", body: "End your shower with 30 seconds of pure cold water to build mental resilience." },
    { title: "Review Your Finances", body: "Log into your bank account and review your spending for the last 3 days without judgment." },
    { title: "Journal Your Fears", body: "Write down the three things you are most afraid of right now, then write one step to mitigate each." },
    { title: "Call a Relative", body: "Call a family member you haven't spoken to in a while. Just listen to them." },
    { title: "Donate One Item", body: "Find one item in your home you no longer use and put it in a box to donate." },
    { title: "Sleep 8 Hours", body: "Commit to being in bed 8.5 hours before you need to wake up tonight." },
    { title: "No Multitasking", body: "For 2 hours today, do only one thing at a time. No eating while watching TV, no scrolling while walking." },
    { title: "Drink Green Tea", body: "Replace your afternoon coffee with a cup of green tea or water." },
    { title: "Forgive Yourself", body: "Identify a past mistake you are still holding onto. Say aloud: 'I forgive myself and I release this.'" },
    { title: "Plan Tomorrow Today", body: "Write down your 3 most important tasks for tomorrow before you go to sleep tonight." },
    { title: "Stand Up Straight", body: "Set a timer to go off every 2 hours. When it rings, correct your posture." },
    { title: "Listen Deeply", body: "In your next conversation, wait a full 2 seconds after the other person finishes speaking before you reply." },
    { title: "The Creative Outlet", body: "Spend 15 minutes drawing, writing, or playing music, purely for the joy of it, with no goal." },
    { title: "Embrace Discomfort", body: "Do one task today that you have been actively avoiding because it feels uncomfortable." }
  ],
  "Positive Affirmation": [
    { title: "I Am Returning", body: "I am not lost. I am returning to myself one clear choice at a time." },
    { title: "I Can Practice", body: "I can practice courage, focus, patience, and love today." },
    { title: "Worthy of Success", body: "I am worthy of the success and peace I am working towards. I accept good things into my life." },
    { title: "Inner Strength", body: "I possess the inner strength to overcome any obstacle placed in my path." },
    { title: "Peaceful Mind", body: "My mind is a calm lake. I observe my thoughts without being swept away by them." },
    { title: "Abundance", body: "I am surrounded by abundance. Opportunities flow to me naturally and easily." },
    { title: "Self-Compassion", body: "I treat myself with the same kindness and understanding that I offer to my closest friends." },
    { title: "Growing Every Day", body: "Every mistake is a lesson. I am constantly learning, growing, and evolving." },
    { title: "Radiating Love", body: "I radiate love and positivity, and I attract the same energy from the universe." },
    { title: "In Control", body: "I am in control of my reactions. I choose to respond with grace and wisdom." },
    { title: "Health and Vitality", body: "My body is strong, my mind is sharp, and my spirit is vibrant with life." },
    { title: "Trust the Journey", body: "I trust the timing of my life. Everything is unfolding perfectly for my highest good." },
    { title: "Fearless Heart", body: "I act in spite of fear. Courage is my natural state of being." },
    { title: "Joyful Presence", body: "I find joy in the present moment. Right now, I have everything I need." },
    { title: "Boundless Creativity", body: "My creative potential is infinite. Ideas flow through me effortlessly." },
    { title: "Financial Freedom", body: "I am capable of creating immense value, and I am open to receiving wealth in return." },
    { title: "Forgiveness", body: "I forgive those who have wronged me, freeing myself from the burden of resentment." },
    { title: "Unstoppable Momentum", body: "Every small step I take builds unstoppable momentum toward my dreams." },
    { title: "Deep Sleep", body: "I release the day's worries and invite deep, restorative sleep into my night." },
    { title: "Clear Vision", body: "My vision for my future is clear, and my daily actions align with that vision." },
    { title: "Radiant Confidence", body: "I step into every room with confidence, knowing my unique value." },
    { title: "Embracing Change", body: "I welcome change as a beautiful opportunity to experience more of life." },
    { title: "Healing Energy", body: "Healing energy flows through every cell of my body, restoring me to perfect health." },
    { title: "Powerful Voice", body: "My voice matters. I speak my truth with clarity, kindness, and conviction." },
    { title: "Grateful Heart", body: "I am profoundly grateful for the simple miracles that surround me every day." },
    { title: "Resilient Spirit", body: "I bounce back from setbacks quickly and with even greater determination." },
    { title: "Magnetic Aura", body: "I attract supportive, loving, and inspiring people into my life." },
    { title: "Focus and Clarity", body: "My mind is sharp, focused, and capable of deep concentration." },
    { title: "Divine Guidance", body: "I am guided by a higher wisdom. I trust my intuition implicitly." },
    { title: "Limitless Potential", body: "I am not bound by my past. My potential is entirely limitless." },
    { title: "Deserving of Happiness", body: "I am inherently deserving of deep, lasting, and unconditional happiness." }
  ],
  "Daily Mission": [
    { title: "Three Priorities", body: "Choose three priorities. Finish the first before negotiating with distraction." },
    { title: "Body And Mind", body: "Drink water, move for ten minutes, and write one sentence that tells the truth." },
    { title: "Clear the Inbox", body: "Process your email inbox to zero. Delete, delegate, or reply to everything." },
    { title: "Deep Work Block", body: "Complete 90 minutes of focused, uninterrupted work on your most important project." },
    { title: "The 15-Minute Tidy", body: "Set a timer for 15 minutes and aggressively clean your immediate living area." },
    { title: "Learn Something New", body: "Watch a documentary or read an article about a subject you know nothing about." },
    { title: "Reach Out", body: "Contact one professional connection to check in, with no agenda other than saying hello." },
    { title: "Financial Audit", body: "Review all your monthly subscriptions and cancel at least one you don't use." },
    { title: "Meal Prep", body: "Prepare healthy meals for the next two days to save time and willpower." },
    { title: "Digital Detox", body: "Turn off all notifications on your phone for the entire day, except for phone calls." },
    { title: "The Gratitude Note", body: "Write a physical thank-you note to someone and mail or hand it to them." },
    { title: "Review Your Goals", body: "Read your yearly goals out loud and schedule one action step for each this week." },
    { title: "Fix the Broken", body: "Repair or replace one thing in your house that has been broken for over a month." },
    { title: "The Brain Dump", body: "Write down every single lingering thought, task, or worry on a blank piece of paper." },
    { title: "Plan the Week", body: "Spend 30 minutes mapping out your entire schedule and priorities for the upcoming week." },
    { title: "Hydration Goal", body: "Drink exactly 3 liters (or 100 oz) of water today." },
    { title: "The Evening Routine", body: "Execute a perfect 30-minute wind-down routine tonight before getting into bed." },
    { title: "Read 30 Pages", body: "Dedicate time today to read 30 pages of an educational or inspiring book." },
    { title: "The Hardest Task First", body: "Identify the task you are dreading the most and complete it immediately upon waking." },
    { title: "Optimize Your Sleep", body: "Make your bedroom completely dark, cool, and silent for tonight's sleep." },
    { title: "Connect with Nature", body: "Spend 20 minutes outside in a park, forest, or near water, away from concrete." },
    { title: "The Mindful Commute", body: "Drive or commute today without any music or podcasts. Just observe." },
    { title: "Empty the Trash", body: "Take out all the trash in the house, physically and digitally (empty computer recycle bin)." },
    { title: "The Favor", body: "Do a favor for a coworker or friend without them asking for it." },
    { title: "Analyze Your Diet", body: "Track every single calorie and macronutrient you consume today to understand your habits." },
    { title: "The Future Self", body: "Write a letter to yourself 5 years from now, detailing what you hope you have achieved." },
    { title: "Sweat", body: "Engage in physical activity intense enough to make you sweat for at least 20 minutes." },
    { title: "The Compliment Challenge", body: "Give 3 genuine compliments to 3 different people today." },
    { title: "Review Mistakes", body: "Write down a recent failure, extract 3 lessons from it, and let the negative emotion go." },
    { title: "Organize Digital Files", body: "Organize your computer desktop and documents folder into clean, logical categories." },
    { title: "The Rest Day", body: "Your mission today is aggressive recovery. No hard work. Rest your body and mind completely." }
  ],
  "Visualization Exercise": [
    { title: "Future Room", body: "Close your eyes and picture tomorrow night. See yourself proud of one completed action. Now name that action." },
    { title: "Calm Self", body: "Imagine your calmest self entering the room. Notice posture, breath, and voice. Borrow that energy for five minutes." },
    { title: "The Mountain Peak", body: "Visualize yourself standing on a high peak. The wind is cool. Below you are all your past struggles, small and distant." },
    { title: "The Shield of Light", body: "Imagine a sphere of warm, golden light surrounding your body. It repels negativity and absorbs only peace." },
    { title: "Meeting Your Mentor", body: "Picture sitting across from the wisest person you can imagine. Ask them your biggest question, and listen to their answer." },
    { title: "The Perfect Day", body: "Walk through your ideal day from waking up to falling asleep. Feel the emotions of success, joy, and profound peace." },
    { title: "Roots in the Earth", body: "Imagine thick, strong roots extending from your feet deep into the earth. Feel the stability and groundedness it brings." },
    { title: "The Healing River", body: "Visualize a cool, crystal-clear river. Step into it and feel it washing away your stress, pain, and anxiety." },
    { title: "The Empty Theater", body: "Picture your mind as an empty theater. Let your anxious thoughts play on the screen while you sit safely in the back row." },
    { title: "The Heavy Backpack", body: "Imagine taking off a heavy backpack filled with rocks representing your worries. Feel the lightness in your shoulders." },
    { title: "The Golden Thread", body: "Visualize a golden thread pulling you gently upward from the crown of your head, straightening your spine and aligning your energy." },
    { title: "The Success Podium", body: "See yourself receiving an award for your life's work. Hear the applause and feel the deep satisfaction in your chest." },
    { title: "The Peaceful Forest", body: "Walk slowly through a lush, green forest in your mind. Smell the pine, hear the leaves, and breathe the crisp air." },
    { title: "The Blank Canvas", body: "Imagine your future as a massive, pristine white canvas. You hold the brush. What color do you paint first?" },
    { title: "The Dial of Emotion", body: "Visualize a control panel in your mind. Find the dial labeled 'Anxiety' and slowly turn it down to zero." },
    { title: "The Mirror of Truth", body: "Look into an imaginary mirror. See past your physical flaws and recognize the brilliant, radiant soul shining beneath." },
    { title: "The Ascending Balloon", body: "Put all your negative thoughts into a large red balloon. Let it go and watch it float away until it disappears." },
    { title: "The Inner Child", body: "Visualize yourself at 5 years old. Give that child a hug and tell them they are safe, loved, and capable." },
    { title: "The Armor of Confidence", body: "Imagine putting on a suit of shining armor. It is weightless, but it makes you feel completely invincible to criticism." },
    { title: "The Symphony of Life", body: "Picture yourself as the conductor of a grand orchestra. You control the tempo, the volume, and the harmony of your life." },
    { title: "The Sun's Warmth", body: "Imagine the warm rays of the sun penetrating your skin, filling you with golden energy and vitality." },
    { title: "The Book of Life", body: "Visualize a massive book containing your life story. Turn to a blank page and write the boldest next chapter you can imagine." },
    { title: "The Flowing Stream", body: "See your thoughts as leaves floating down a gentle stream. Don't grab them; just watch them pass by." },
    { title: "The Fortress of Focus", body: "Imagine building thick brick walls around your workspace. Distractions bounce off the walls, leaving you in pure concentration." },
    { title: "The Healing Light", body: "Visualize a brilliant white light hovering over any part of your body that feels pain or tension, slowly dissolving the discomfort." },
    { title: "The Applause of Loved Ones", body: "Picture all the people who love you standing in a circle, clapping for your effort and resilience today." },
    { title: "The Seed of Potential", body: "Imagine planting a tiny glowing seed in fertile soil. Watch it rapidly grow into a massive, blossoming tree representing your potential." },
    { title: "The Vault of Memories", body: "Walk into a secure vault. Place your painful memories in a safe, lock it, and walk out into the bright sunlight." },
    { title: "The Breath of Fire", body: "With every inhale, imagine breathing in powerful, vibrant fire energy. With every exhale, breathe out sluggishness." },
    { title: "The Cosmic Perspective", body: "Zoom out from your body, to your city, to the Earth, to the galaxy. Realize how small your current problem truly is." },
    { title: "The Finish Line", body: "Visualize yourself crossing the finish line of a marathon. Feel the exhaustion, but more importantly, the absolute triumph." }
  ],
  "Morning Motivation": [
    { title: "Open Cleanly", body: "Start the day without asking for permission from yesterday. Make your first action clean and deliberate." },
    { title: "Light First", body: "Let the morning be simple: water, breath, one priority, and a little faith." },
    { title: "The First Victory", body: "Making your bed is the first victory of the day. It sets the tone for a cascade of success." },
    { title: "Morning Silence", body: "Protect the first 30 minutes of your day from the noise of the world. Let your own thoughts speak first." },
    { title: "Sunlight and Water", body: "You are a complex plant. Drink a glass of water and get sunlight in your eyes immediately. The rest will follow." },
    { title: "The Blank Slate", body: "Yesterday ended last night. Today is a pristine blank slate. Do not pollute it with old regrets." },
    { title: "Win the Morning", body: "Win the first hour of the day, and you have already won the battle for the entire day." },
    { title: "Gratitude Awakening", body: "Before your feet touch the floor, think of three things you are grateful for. It changes the chemical balance in your brain." },
    { title: "Purposeful Rise", body: "Do not hit snooze. Rise immediately with the fierce determination to execute your mission today." },
    { title: "The Gift of Breath", body: "Take five deep breaths. You have been given the gift of another day of life. Do not waste it." },
    { title: "Protect Your Energy", body: "Do not check the news or social media until you have accomplished your first major task." },
    { title: "Set the Intention", body: "Decide right now how you want to feel today. Joyful? Productive? Calm? Act as if you already feel it." },
    { title: "The Morning Stretch", body: "Move your body. Wake up your nervous system. A stagnant body creates a stagnant mind." },
    { title: "Nourish the Machine", body: "Eat a breakfast that honors your body's need for fuel, not just your tongue's desire for sugar." },
    { title: "Review the Plan", body: "Look at your goals for the day. Visualize yourself completing each one with ease and excellence." },
    { title: "Embrace the Grind", body: "Today will have challenges. Smile at them in advance. You are built to overcome friction." },
    { title: "Speak Life", body: "Look in the mirror and declare one positive truth about yourself out loud." },
    { title: "The Commute of Champions", body: "Use your travel time to listen to an audiobook or podcast that makes you smarter or stronger." },
    { title: "Leave Early", body: "Give yourself the luxury of being 10 minutes early today. Eliminate the stress of rushing." },
    { title: "Dress for Success", body: "Put on clothes that make you feel powerful and competent. Your outer shell influences your inner state." },
    { title: "The Uncluttered Space", body: "Clear your desk before you start working. Visual clarity creates mental clarity." },
    { title: "Swallow the Frog", body: "Do the hardest, most uncomfortable task first. The rest of the day will feel like a breeze." },
    { title: "Radiate Positivity", body: "Decide to be the person who brings good energy into the office or your home today." },
    { title: "Patience with Delays", body: "If traffic is bad or coffee spills, take a breath. Do not let a 5-minute inconvenience ruin a 24-hour day." },
    { title: "Focus on the Step", body: "Do not worry about the mountain of work. Just focus on the very next step in front of you." },
    { title: "The Mindful Cup", body: "Drink your morning coffee or tea with absolute presence. Notice the warmth, the smell, the taste." },
    { title: "Remember Your 'Why'", body: "Remind yourself why you are working so hard. Keep the ultimate goal burning in your mind." },
    { title: "Forgive Yesterday", body: "If you failed yesterday, leave it in the tomb of the past. Today is a resurrection of your potential." },
    { title: "Seek Opportunities", body: "Keep your eyes open today. The universe is hiding opportunities in plain sight." },
    { title: "Be the Light", body: "The world can be dark. Decide this morning that you will be a source of light and kindness." },
    { title: "Ready for Action", body: "You are rested. You are focused. You are capable. Now, go execute." }
  ],
  "Night Reflection": [
    { title: "Close With Grace", body: "Write what you learned, forgive what was messy, and prepare one gentle win for tomorrow." },
    { title: "Soft Audit", body: "Ask: What gave energy? What drained energy? What will I protect tomorrow?" },
    { title: "Release the Day", body: "You cannot change what happened today. Release your grip on it, and let sleep heal you." },
    { title: "The 3 Wins", body: "Write down three things you accomplished today, no matter how small. Celebrate your momentum." },
    { title: "Forgive Yourself", body: "You made mistakes today. That is human. Forgive yourself completely before closing your eyes." },
    { title: "Digital Sunset", body: "Turn off all glowing screens one hour before bed. Let your brain know it is time to rest." },
    { title: "Prepare the Launchpad", body: "Lay out your clothes and prep your workspace for tomorrow morning. Make tomorrow easy." },
    { title: "The Gratitude Scan", body: "Scan your body from head to toe, thanking each part for carrying you through the day." },
    { title: "Read for Peace", body: "Read fiction or philosophy to disconnect your brain from the urgent stresses of work." },
    { title: "The Brain Dump", body: "If your mind is racing, write every thought down on paper. Get them out of your head so you can sleep." },
    { title: "Forgive Others", body: "Do not take resentment to bed. Forgive those who annoyed you; they are fighting their own battles." },
    { title: "Acknowledge the Effort", body: "You tried your best today with the energy you had. That is always enough." },
    { title: "The Gentle Stretch", body: "Release the physical tension of the day with 5 minutes of slow, deep stretching." },
    { title: "Review the Goal", body: "Look at your ultimate life goal one last time before sleep, letting your subconscious work on it overnight." },
    { title: "Cool the Room", body: "Drop the temperature in your bedroom. A cool environment promotes deep, restorative sleep." },
    { title: "The Breath of Calm", body: "Inhale for 4 seconds, hold for 7, exhale for 8. Repeat four times to shut down the nervous system." },
    { title: "Appreciate the Silence", body: "The world is finally quiet. Enjoy the profound peace of the night." },
    { title: "No Late Regrets", body: "Midnight is the wrong time to analyze your life choices. Save the heavy thinking for the morning light." },
    { title: "The Clean Kitchen", body: "Wake up to a clean house by spending 10 minutes tidying up the kitchen before bed." },
    { title: "Reflect on Interactions", body: "Did you speak with kindness today? If not, resolve to be softer tomorrow." },
    { title: "The Gift of Sleep", body: "Sleep is not a waste of time; it is the ultimate performance enhancer. Welcome it." },
    { title: "Disconnect from Work", body: "Do not check your work email in bed. Your rest time is sacred. Protect it fiercely." },
    { title: "The Body's Wisdom", body: "Listen to your body. If it is exhausted, do not force it to stay awake. Go to sleep." },
    { title: "Trust the Process", body: "You might not be where you want to be yet, but you are one day closer. Trust the journey." },
    { title: "Send Good Will", body: "Mentally send love and good health to your friends and family before drifting off." },
    { title: "The Blank Page", body: "Tomorrow is a blank page waiting to be written. Rest now so you can write a masterpiece." },
    { title: "Acknowledge the Privilege", body: "Having a warm bed and a safe place to sleep is a tremendous privilege. Feel the gratitude." },
    { title: "Let Go of Control", body: "You cannot control the universe while you sleep. Surrender control and let the world spin without you." },
    { title: "The Healing Dark", body: "Embrace the darkness of the room. It is a healing blanket for your overstimulated eyes." },
    { title: "Final Prayer", body: "Offer a silent word of thanks to the Divine for guiding you safely through another day." },
    { title: "Peaceful Surrender", body: "I am safe. I am loved. My work for today is done. I surrender to sleep." }
  ]
};
